### ISSUE TITLE
Feature request, read all modbus meters and also log voltage, cos phi etc

### ISSUE THREAD

**Issue by fluppie** [serkri/SmartEVSE-3#132]
Currently I have a ESP32 with modbus shield from [enri.nl ](https://enri.nl/pcb/?page=modbus) to read all parameters / all modbusmeters. This gives 2 modbus masters which is far from ideal. I don't know if it's a lot of work to read out more registers than current and power as well as kWh import / export.

Screenshot of the ESP32 with ESPEasy software:
![afbeelding](https://user-images.githubusercontent.com/8402106/235345830-c500ca64-5716-44ee-85e3-7ebbf9a5ef50.png)

The Nan values are because of modbus collisions. I think the SmartEVSE is requesting every 2 seconds data on the modbus. My mainsmeter is at 15s intervals and the PV and EV meter are at 60s intervals. To limit the number of collisions.

List with all available registers:
https://github.com/reaper7/SDM_Energy_Meter/blob/master/SDM.h

![afbeelding](https://user-images.githubusercontent.com/8402106/235346090-69749198-abb9-4149-97ed-48e7708b548e.png)

Just a question, if not I keep using it like this. On the other hand I can save a ESP32, a 5V power supply and modbus collisions :).

**Comment by Ferforfaen** [comment]
I would love that! 

I have tried to do readouts with two masters, but failed.

**Comment by dingo35** [comment]
I am thinking about a sort of configurable gateway from modbus to REST API....

**Comment by fluppie** [comment]
Or an implementation of Modbus TCP, so all Modbus RTU devices can also be read/controlled over Modbus TCP. But I think it would be enough to go full read-out with SmartEVSE v3 and then using the REST API to send Modbus meter data to Home Assistant or other HA systems.
I do like the fact that inter SmartEVSE communication is RTU RS485, so Sensorbox can be far away of the SmartEVSE or for example one electrical cabinet with 4 SmartEVSE's talking to another board with 4 EVSE's 20-30m away. Same story for the sensorbox. In large industrial sites the main board where power from the netdistributor or own local transformator can be quite far away from the electrical cabinets with SmartEVSE's.

**Comment by dingo35** [comment]
[modbus-tcp-bridge.zip](https://github.com/serkri/SmartEVSE-3/files/11364568/modbus-tcp-bridge.zip)

In this version your MainsMeter, EVMeter and PVMeter present themselves at port 502 of your SmartEVSE, with the modbus-tcp protocol; so this makes it possible for you to use whatever modbus function you want on whatever modbus register you want.
E.g. my MainsMeter is at slave address 0x0a, so this command reads register 70decimal and following:
mbpoll -a10 -t 3:hex -r 70 -c 10 10.0.0.76 

Please test, have fun!

**Comment by fluppie** [comment]
Looks like it's working can it interfere with the SmartEVSE RTU modbus polling? I mean can the TCP requests from HA happen on the same time as the SmartEVSE is polling this data from the RTU modbus?
![afbeelding](https://user-images.githubusercontent.com/8402106/235449542-f93a6b99-b623-4869-9363-3657f1111902.png)

Because sometimes I see this:
![afbeelding](https://user-images.githubusercontent.com/8402106/235449631-074700a3-d02a-4457-ae8c-89d54f320803.png)

Home Assistant yaml config
```
modbus: 
  - type: tcp
    host: 192.168.1.119 # ip van smartevse v3
    port: 502
    name: "smartevsev3modbustcp"
    close_comm_on_error: true
    delay: 3
    timeout: 5
    sensors:
      - name: sdm230_phase_1_line_to_neutral_volts
        slave: 101
        address: 0
        input_type: input
        count: 2
        precision: 2
        data_type: float32
        unit_of_measurement: V
        device_class: voltage
        scan_interval: 10
      - name: sdm230_phase_1_current
        slave: 101
        address: 6
        input_type: input
        count: 2
        precision: 2
        data_type: float32
        unit_of_measurement: A
        device_class: current
        scan_interval: 10
      - name: sdm230_phase_1_power
        slave: 101
        address: 12
        input_type: input
        count: 2
        precision: 3
        data_type: float32
        unit_of_measurement: W
        device_class: power
      - name: sdm230_phase_1_va
        slave: 101
        address: 18
        input_type: input
        count: 2
        precision: 2
        data_type: float32
        unit_of_measurement: VA
        device_class: power
```
