### ISSUE TITLE
Mqtt: home battery set to 0

### ISSUE THREAD

**Issue by stevoh6** [serkri/SmartEVSE-3#170]
Hi, im feeding SmartEvse with data via mqtt. I see strange behaviour, when I send MainsMeter data, home battery is set to 0 until I resend HomeBatteryCurrent data again. Those data are comming in diferrent intervals, because they are now separated. In API we send those data together.

**Comment by dingo35** [comment]
Ok I don't have a home-battery, and I don't feed MainsMeter currents through the API, so I'm not talking from practical experience here; but we never documented the homebatterycurrent API being valid for Solar Mode only. Now Normal Mode doesnt make any sense, but wouldn't Smart Mode be an understandable use case?

So I have 25A MainsConnection, and a 5A homebattery feed, so now I would like to charge 30A in Smart Mode?

**Comment by arpiecodes** [comment]
I also have no idea to be honest. @stevoh6 what's your use-case by using the battery current?

**Comment by stevoh6** [comment]
Use case is simple, solar panels + home battery + solar mode on evse.  I was cecking/observing flowing data in mqtt server and I notice, that battery is until "battery update is send" reset to 0 after evse receive currents. I will check it more precicely nce again. But I have two problems with home battery, second one is major:
1. > I would like to see battery info even Im on normal mode on web ( so  I doesnt need to check another web page to get this info in order set override currents) -not critical.
2. > when Im in solar mode, the changes in currents are too frequent. Im feeding evse via mqtt with currents every (5-10s > when values are updated in HA >from inverter). Smart evse is trying agrresively adjust currents and every 5s the energy flow in my house is crazy, first 5 seconds Im importing from grid, second 5 seconds im importing from battery, third 5s im importing from grid and so on. I woul like to stabilize that, for example adujt it every 1-5mins, ignore some small values like +-200w,  Most of us are fine, when for short period of time ( clouds) we feed car charging from home battery. 

I was trying to sme crazy automations to adjust "battery data before sending them to evse, but without any feasible luck.
```
alias: .EVSE set MQTT HomeBatteryCurrent from HA
trigger:
  - platform: state
    entity_id:
      - sensor.battery_current
    for:
      hours: 0
      minutes: 0
      seconds: 1
action:
  - service: mqtt.publish
    data_template:
      topic: SmartEVSE-15780/Set/HomeBatteryCurrent
      payload: >-
        {% set battery_current10 = states('sensor.battery_current') | float * 10
        * (-1) %} {% set charging = iif(battery_current10 > -10, true , false)
        %} {% set over_charging = iif((30 > battery_current10 ) , false , true)
        %} {{ iif(charging, iif(over_charging, battery_current10 - 30, 0 ),
        battery_current10 - 10 ) }}
```
